services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'
            $model: '%env(OPENAI_MODEL)%'

    # Optional: weitere Service-Definitionen, z.B.:
    # App\:
    #     resource: '../src/'
    #     exclude: '../src/{DependencyInjection,Entity,Kernel.php}'
